Repository SMU-SATTO/SATTO-Server, pull requests merged in 2024-08, with the labels that each got.

#170 ✨ [FEATURE] 이벤트 카테고리 목록 조회 수정
  src/main/java/com/example/satto/config/EmailConfig.java
  src/main/java/com/example/satto/domain/event/controller/EventController.java
  src/main/java/com/example/satto/domain/event/dto/EventCategoryResponseDto.java
  src/main/java/com/example/satto/domain/event/entity/Event.java
  src/main/java/com/example/satto/domain/event/service/EventService.java
  src/main/java/com/example/satto/domain/event/service/impl/EventServiceImpl.java
Labels: :sparkles: Feature

#171 :bug: [FIX] 이벤트 검증 예외 처리 추가, 쿼리문 수정, ListDto 해체
  src/main/java/com/example/satto/domain/event/controller/EventController.java
  src/main/java/com/example/satto/domain/event/controller/PhotoContestController.java
  src/main/java/com/example/satto/domain/event/controller/TimetableContestController.java
  src/main/java/com/example/satto/domain/event/dto/EventCategoryListResponseDto.java
  src/main/java/com/example/satto/domain/event/dto/PhotoContestListResponseDto.java
  src/main/java/com/example/satto/domain/event/dto/TimetableContestListResponseDto.java
  src/main/java/com/example/satto/domain/event/repository/EventRepository.java
  src/main/java/com/example/satto/domain/event/repository/EventRepositoryCustom.java
  src/main/java/com/example/satto/domain/event/repository/PhotoContestRepository.java
  src/main/java/com/example/satto/domain/event/repository/TimetableContestDislikeRepository.java
  src/main/java/com/example/satto/domain/event/repository/TimetableContestLikeRepository.java
  src/main/java/com/example/satto/domain/event/repository/TimetableContestRepository.java
  src/main/java/com/example/satto/domain/event/repository/impl/EventRepositoryCustomImpl.java
  src/main/java/com/example/satto/domain/event/service/EventService.java
  src/main/java/com/example/satto/domain/event/service/impl/EventServiceImpl.java
  src/main/java/com/example/satto/global/common/code/status/ErrorStatus.java
Labels: :bug: Bug

#173 refactor : 회원탈퇴시 시간표 삭제
  src/main/java/com/example/satto/domain/timeTable/repository/TimeTableRepository.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
Labels: :recycle: Refactor

#174 :bug: [FIX] 카테고리별 이벤트 테이블 중복 고유값 설정으로 인한 오류 수정
  src/main/java/com/example/satto/domain/event/entity/Event.java
  src/main/java/com/example/satto/domain/event/entity/photoContest/PhotoContest.java
  src/main/java/com/example/satto/domain/event/entity/timetableContest/TimetableContest.java
Labels: :bug: Bug

#177 [Feature] 프로필 이미지 수정/삭제 구현
  src/main/java/com/example/satto/config/S3Config.java
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/converter/UsersConverter.java
  src/main/java/com/example/satto/domain/users/dto/SaveProfileUrlRequest.java
  src/main/java/com/example/satto/domain/users/dto/UsersRequestDTO.java
  src/main/java/com/example/satto/domain/users/dto/UsersResponseDTO.java
  src/main/java/com/example/satto/domain/users/repository/UsersRepository.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
  src/main/java/com/example/satto/s3/S3Manager.java
Labels: :sparkles: Feature, 🧹Chore

#178 :recycle: [REFACTOR] 이벤트 API 통합
  src/main/java/com/example/satto/domain/event/controller/EventController.java
  src/main/java/com/example/satto/domain/event/controller/PhotoContestController.java
  src/main/java/com/example/satto/domain/event/controller/TimetableContestController.java
  src/main/java/com/example/satto/domain/event/dto/ContestResponseDto.java
  src/main/java/com/example/satto/domain/event/dto/PhotoContestResponseDto.java
  src/main/java/com/example/satto/domain/event/entity/Contest.java
  src/main/java/com/example/satto/domain/event/entity/ContestDislike.java
  src/main/java/com/example/satto/domain/event/entity/ContestLike.java
  src/main/java/com/example/satto/domain/event/entity/Event.java
  src/main/java/com/example/satto/domain/event/entity/photoContest/PhotoContestLike.java
  src/main/java/com/example/satto/domain/event/entity/timetableContest/TimetableContest.java
  src/main/java/com/example/satto/domain/event/entity/timetableContest/TimetableContestLike.java
  src/main/java/com/example/satto/domain/event/repository/ContestDislikeRepository.java
  src/main/java/com/example/satto/domain/event/repository/ContestLikeRepository.java
  src/main/java/com/example/satto/domain/event/repository/ContestRepository.java
  src/main/java/com/example/satto/domain/event/repository/PhotoContestDislikeRepository.java
  src/main/java/com/example/satto/domain/event/repository/PhotoContestLikeRepository.java
  src/main/java/com/example/satto/domain/event/repository/TimetableContestDislikeRepository.java
  src/main/java/com/example/satto/domain/event/repository/TimetableContestLikeRepository.java
  src/main/java/com/example/satto/domain/event/repository/TimetableContestRepository.java
  src/main/java/com/example/satto/domain/event/service/EventService.java
  src/main/java/com/example/satto/domain/event/service/impl/EventServiceImpl.java
  src/main/java/com/example/satto/domain/users/entity/Users.java
Labels: :recycle: Refactor

#179 :sparkles: [FEATURE] 이벤트 참여 조회 Dto 속성 추가
  src/main/java/com/example/satto/domain/event/controller/EventController.java
  src/main/java/com/example/satto/domain/event/dto/ContestResponseDto.java
  src/main/java/com/example/satto/domain/event/repository/ContestDislikeRepository.java
  src/main/java/com/example/satto/domain/event/repository/ContestLikeRepository.java
  src/main/java/com/example/satto/domain/event/service/EventService.java
  src/main/java/com/example/satto/domain/event/service/impl/EventServiceImpl.java
Labels: :sparkles: Feature

#181 feat: 친구와 시간표 비교 기능 추가
  src/main/java/com/example/satto/domain/timeTable/controller/TimeTableController.java
  src/main/java/com/example/satto/domain/timeTable/dto/CompareTimeTableRequestDTO.java
  src/main/java/com/example/satto/domain/timeTable/repository/TimeTableRepository.java
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
  src/main/java/com/example/satto/domain/timeTableLecture/repository/TimeTableLectureRepository.java
Labels: :sparkles: Feature

#182 [feature] 임시 비밀번호 발급 / 이메일 변경 추가
  src/main/java/com/example/satto/domain/mail/controller/MailController.java
  src/main/java/com/example/satto/domain/mail/dto/EmailRequestDTO.java
  src/main/java/com/example/satto/domain/mail/service/EmailService.java
  src/main/java/com/example/satto/domain/mail/service/Impl/EmailServiceImpl.java
  src/main/java/com/example/satto/domain/users/dto/UsersRequestDTO.java
  src/main/java/com/example/satto/domain/users/repository/UsersRepository.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#185 [Chore] 비밀번호 재설정 api
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/dto/UsersRequestDTO.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
  src/main/java/com/example/satto/global/common/code/status/ErrorStatus.java
Labels: 🧹Chore
