Repository SMU-SATTO/SATTO-Server, pull requests merged in 2024-09, with the labels that each got.

#187 refactor : 시간표 비교 기능 응답 수정
  src/main/java/com/example/satto/domain/timeTable/controller/TimeTableController.java
  src/main/java/com/example/satto/domain/timeTable/repository/TimeTableRepository.java
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
  src/main/java/com/example/satto/domain/timeTableLecture/repository/TimeTableLectureRepository.java
Labels: :recycle: Refactor

#189 [Chore] PatchMapping에 consumes 속성 추가
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
Labels: 🧹Chore

#191 [Chore] 계정 공개시 팔로우 요청 수락 목록 문제
  src/main/java/com/example/satto/domain/follow/service/FollowService.java
  src/main/java/com/example/satto/domain/follow/service/Impl/FollowServiceImpl.java
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
Labels: 🧹Chore

#193 [Bug] 회원 탈퇴, 시간표 관련 외래키 문제
  src/main/java/com/example/satto/domain/timeTableLecture/repository/TimeTableLectureRepository.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
Labels: :bug: Bug

#196 [Bug] 공개/비공개 전환에 따른 팔로우 요청 버그 수정
  src/main/java/com/example/satto/domain/follow/repository/FollowRepository.java
  src/main/java/com/example/satto/domain/follow/service/Impl/FollowServiceImpl.java
Labels: :bug: Bug
