Repository SMU-SATTO/SATTO-Server, pull requests merged in 2024-06, with the labels that each got.

#48 [REFACTOR] 로그인 기능 Rollback
  build.gradle
  src/main/java/com/example/satto/config/security/JwtService.java
  src/main/java/com/example/satto/config/security/auth/AuthenticationService.java
  src/main/java/com/example/satto/config/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/satto/config/security/handler/LogoutService.java
  src/main/java/com/example/satto/config/security/token/Token.java
  src/main/java/com/example/satto/config/security/token/TokenRepository.java
  src/main/java/com/example/satto/config/security/userDetails/CustomUserDetails.java
  src/main/java/com/example/satto/config/security/userDetails/CustomUserDetailsService.java
  src/main/java/com/example/satto/domain/course/controller/CourseController.java
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/global/annotation/AuthUser.java
  src/main/java/com/example/satto/global/annotation/AuthUserArgumentResolver.java
  src/main/java/com/example/satto/util/JwtUtil.java
  src/main/java/com/example/satto/util/dto/JwtDto.java
Labels: :recycle: Refactor

#51 [Feature] 회원가입 로직 추가
  src/main/java/com/example/satto/config/security/auth/AuthenticationController.java
  src/main/java/com/example/satto/config/security/auth/AuthenticationResponse.java
  src/main/java/com/example/satto/config/security/auth/AuthenticationService.java
  src/main/java/com/example/satto/config/security/auth/RegisterRequest.java
  src/main/java/com/example/satto/domain/mail/controller/MailController.java
  src/main/java/com/example/satto/domain/mail/dto/EmailRequestDTO.java
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/dto/UsersRequestDTO.java
  src/main/java/com/example/satto/domain/users/repository/UsersRepository.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#61 feat:회원 탈퇴 기능 추가
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#64 feat: 회원 탈퇴 수정2
  src/main/java/com/example/satto/domain/follow/repository/FollowRepository.java
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/entity/Users.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#68 feat: 토큰 블랙리스트 구현 테스트 완료 / 불필요 코드 삭제
  src/main/java/com/example/satto/config/security/handler/LogoutService.java
Labels: :sparkles: Feature

#70 feat: 비밀번호 제약조건 삭제
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/dto/UsersRequestDTO.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#71 ✨ [FEATURE] 운영 DB 삽입 기능 관련 Entity 수정, RDS 데이터 삽입 Test 진행
  src/main/java/com/example/satto/domain/course/converter/CourseConverter.java
  src/main/java/com/example/satto/domain/course/converter/PreviousLecturesConverter.java
  src/main/java/com/example/satto/domain/course/entity/Course.java
  src/main/java/com/example/satto/domain/course/entity/PreviousLecture.java
  src/main/java/com/example/satto/domain/currentLecture/controller/CurrentLectureController.java
  src/main/java/com/example/satto/domain/currentLecture/converter/CurrentLectureConverter.java
  src/main/java/com/example/satto/domain/currentLecture/dto/CurrentLectureListResponseDTO.java
  src/main/java/com/example/satto/domain/currentLecture/dto/CurrentLectureResponseDTO.java
  src/main/java/com/example/satto/domain/currentLecture/entity/CurrentLecture.java
  src/main/java/com/example/satto/domain/currentLecture/repository/CurrentLectureRepository.java
  src/main/java/com/example/satto/domain/currentLecture/service/CurrentLectureService.java
  src/main/java/com/example/satto/domain/timeTable/dto/TimeTableResponseDTO.java
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :sparkles: Feature

#74 feat:회원 가입시 학년 정보 추가
  src/main/java/com/example/satto/config/security/auth/AuthenticationService.java
  src/main/java/com/example/satto/config/security/auth/RegisterRequest.java
Labels: :sparkles: Feature

#76 Doc: swagger summary, description 추가
  src/main/java/com/example/satto/config/security/auth/AuthenticationController.java
  src/main/java/com/example/satto/domain/follow/controller/FollowController.java
  src/main/java/com/example/satto/domain/mail/controller/MailController.java
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
Labels: :memo: Document

#79 style: 유저 isPublic의 자료형 변경
  src/main/java/com/example/satto/config/security/auth/RegisterRequest.java
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/entity/Users.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
Labels: :lipstick: Style

#80 styl: 누락 사항 추가
  src/main/java/com/example/satto/config/security/auth/AuthenticationService.java
Labels: :lipstick: Style

#82 feat: 개인정보 수정 로직 변경
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/converter/UsersConverter.java
  src/main/java/com/example/satto/domain/users/dto/UsersRequestDTO.java
  src/main/java/com/example/satto/domain/users/dto/UsersResponseDTO.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#84 feat: UserConverter에 프로필 이미지 필드 삭제
  src/main/java/com/example/satto/domain/users/converter/UsersConverter.java
Labels: :sparkles: Feature

#86 feat: 이메일 중복 방지 기능 추가 구현
  src/main/java/com/example/satto/domain/mail/controller/MailController.java
  src/main/java/com/example/satto/domain/users/repository/UsersRepository.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#88 feat: Users 도메인 속성 studentId를 String 타입으로 변경 & Follow에서 userId를 studentId로 변경하여 사용
  src/main/java/com/example/satto/config/security/auth/RegisterRequest.java
  src/main/java/com/example/satto/domain/follow/controller/FollowController.java
  src/main/java/com/example/satto/domain/follow/repository/FollowRepository.java
  src/main/java/com/example/satto/domain/follow/service/FollowService.java
  src/main/java/com/example/satto/domain/follow/service/impl/FollowServiceImpl.java
  src/main/java/com/example/satto/domain/mail/controller/MailController.java
  src/main/java/com/example/satto/domain/users/entity/Users.java
  src/main/java/com/example/satto/domain/users/repository/UsersRepository.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#89 feat: FollowController 수정1
  src/main/java/com/example/satto/domain/follow/service/impl/FollowServiceImpl.java
  src/main/java/com/example/satto/domain/users/repository/UsersRepository.java
Labels: :sparkles: Feature

#90 feat: FollowController 수정2
  src/main/java/com/example/satto/domain/follow/service/impl/FollowServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
Labels: :sparkles: Feature

#91 feat: Follow domain 속성에 @CreationTimeStamp 적용
  src/main/java/com/example/satto/domain/follow/entity/Follow.java
Labels: :sparkles: Feature

#93 feat: follow 관련 에러처리 완료
  src/main/java/com/example/satto/domain/follow/controller/FollowController.java
  src/main/java/com/example/satto/domain/follow/service/FollowService.java
  src/main/java/com/example/satto/domain/follow/service/impl/FollowServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
Labels: :sparkles: Feature

#95 refactor: 일부 에러 핸들러 구현
  src/main/java/com/example/satto/domain/follow/service/Impl/FollowServiceImpl.java
  src/main/java/com/example/satto/domain/mail/controller/MailController.java
  src/main/java/com/example/satto/domain/mail/service/Impl/EmailServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/global/common/code/status/ErrorStatus.java
  src/main/java/com/example/satto/global/common/exception/handler/FollowHandler.java
  src/main/java/com/example/satto/global/common/exception/handler/MailHandler.java
  src/main/java/com/example/satto/global/common/exception/handler/UsersHandler.java
Labels: :recycle: Refactor

#97 ✨ Feat: 시간표 정보 수정 기능 추가
  src/main/java/com/example/satto/domain/currentLecture/converter/CurrentLectureConverter.java
  src/main/java/com/example/satto/domain/currentLecture/dto/CurrentLectureResponseDTO.java
  src/main/java/com/example/satto/domain/currentLecture/repository/CurrentLectureRepository.java
  src/main/java/com/example/satto/domain/timeTable/controller/TimeTableController.java
  src/main/java/com/example/satto/domain/timeTable/dto/TimeTableResponseDTO.java
  src/main/java/com/example/satto/domain/timeTable/dto/updateTimeTableRequestDTO.java
  src/main/java/com/example/satto/domain/timeTable/entity/TimeTable.java
  src/main/java/com/example/satto/domain/timeTable/repository/TimeTableRepository.java
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
  src/main/java/com/example/satto/domain/timeTableLecture/entity/TimeTableLecture.java
Labels: :sparkles: Feature

#101 feat:프로필 페이지 api 구현
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/converter/UsersConverter.java
  src/main/java/com/example/satto/domain/users/dto/UsersResponseDTO.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#102 feat: 팔로잉, 팔로워 (학번:이름) 반환 api 구현
  src/main/java/com/example/satto/config/SecurityConfig.java
  src/main/java/com/example/satto/domain/follow/controller/FollowController.java
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#104 refactor : DTO 수정
  src/main/java/com/example/satto/domain/timeTable/dto/TimeTableResponseDTO.java
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :recycle: Refactor

#105 refactor : 비어있는 전공 시간표 생성하는 오류 수정
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :recycle: Refactor

#107 feat: 요청 수락 대기 목록
  src/main/java/com/example/satto/domain/follow/controller/FollowController.java
  src/main/java/com/example/satto/domain/follow/entity/Follow.java
  src/main/java/com/example/satto/domain/follow/repository/FollowRepository.java
  src/main/java/com/example/satto/domain/follow/service/FollowService.java
  src/main/java/com/example/satto/domain/follow/service/Impl/FollowServiceImpl.java
  src/main/java/com/example/satto/domain/users/repository/UsersRepository.java
Labels: :sparkles: Feature

#109 feat: 유저 정보 반환 api
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/converter/UsersConverter.java
  src/main/java/com/example/satto/domain/users/dto/UsersResponseDTO.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
Labels: :sparkles: Feature

#110 feat : requiredLecture 예외처리
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :sparkles: Feature

#111 feat: 상대방 프로필 페이지 방문 api 구현
  src/main/java/com/example/satto/domain/follow/controller/FollowController.java
  src/main/java/com/example/satto/domain/follow/service/Impl/FollowServiceImpl.java
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/repository/UsersRepository.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#114 featuer : 필수로 수강할 강의 예외처리 추가
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :sparkles: Feature

#115 ✨ [FEATURE] 현재 학기 강의 조회 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/example/satto/config/QueryDslConfig.java
  src/main/java/com/example/satto/config/QuerydslConfig.java
  src/main/java/com/example/satto/domain/currentLecture/controller/CurrentLectureController.java
  src/main/java/com/example/satto/domain/currentLecture/dto/CurrentLectureRequestDto.java
  src/main/java/com/example/satto/domain/currentLecture/dto/CurrentLectureResponseDTO.java
  src/main/java/com/example/satto/domain/currentLecture/entity/CurrentLecture.java
  src/main/java/com/example/satto/domain/currentLecture/repository/CurrentLectureRepository.java
  src/main/java/com/example/satto/domain/currentLecture/repository/CurrentLectureRepositoryCustom.java
  src/main/java/com/example/satto/domain/currentLecture/repository/impl/CurrentLectureRepositoryImpl.java
  src/main/java/com/example/satto/domain/currentLecture/service/CurrentLectureService.java
Labels: :sparkles: Feature

#117 feat: 유저 비밀번호 재설정 및 로그인 실패시 에러 처리 추가
  src/main/java/com/example/satto/config/security/auth/AuthenticationController.java
  src/main/java/com/example/satto/config/security/auth/AuthenticationService.java
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/dto/UsersRequestDTO.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
  src/main/java/com/example/satto/global/common/code/status/ErrorStatus.java
Labels: :sparkles: Feature

#118 ✨ [FEATURE] 현재학기강의 조회 request 목록에서 codeSection 항목 제거
  src/main/java/com/example/satto/domain/currentLecture/dto/CurrentLectureRequestDto.java
  src/main/java/com/example/satto/domain/currentLecture/repository/CurrentLectureRepositoryCustom.java
  src/main/java/com/example/satto/domain/currentLecture/repository/impl/CurrentLectureRepositoryImpl.java
  src/main/java/com/example/satto/domain/currentLecture/service/CurrentLectureService.java
Labels: :sparkles: Feature
