Repository SMU-SATTO/SATTO-Server, pull requests merged in 2024-07, with the labels that each got.

#120 hotfix: 유저정보 반환 DTO 수정
  src/main/java/com/example/satto/domain/users/converter/UsersConverter.java
  src/main/java/com/example/satto/domain/users/dto/UsersResponseDTO.java
Labels: :ambulance: HotFix

#123 chore: 유저 DTO에서 email 속성 주석처리
  src/main/java/com/example/satto/domain/users/converter/UsersConverter.java
  src/main/java/com/example/satto/domain/users/dto/UsersResponseDTO.java
Labels: 🧹Chore

#125 chore: 유저 정보 반환 수정
  src/main/java/com/example/satto/config/security/auth/RegisterRequest.java
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/converter/UsersConverter.java
  src/main/java/com/example/satto/domain/users/dto/UsersResponseDTO.java
Labels: 🧹Chore

#129 chore: 유저 정보 반환 DTO 수정
  src/main/java/com/example/satto/domain/users/converter/UsersConverter.java
  src/main/java/com/example/satto/domain/users/dto/UsersResponseDTO.java
Labels: 🧹Chore

#132 chore: 팔로워, 팔로잉 목록 조회 수정
  src/main/java/com/example/satto/domain/users/entity/Users.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
Labels: 🧹Chore

#134 bug: 팔로잉, 팔로워 목록 조회 에러처리
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
Labels: :bug: Bug

#136 refactor : impossibleTimeZone 로직 수정
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :recycle: Refactor

#137 refactor : requiredLect 예외 처리 수정
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :recycle: Refactor

#139 feature : timeTable 이름 수정 기능 추가
  src/main/java/com/example/satto/domain/timeTable/controller/TimeTableController.java
  src/main/java/com/example/satto/domain/timeTable/dto/TimeTableResponseDTO.java
  src/main/java/com/example/satto/domain/timeTable/dto/UpdateTimeTableNameRequestDTO.java
  src/main/java/com/example/satto/domain/timeTable/entity/TimeTable.java
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :sparkles: Feature

#140 ✨ [FEATURE] 현재 학기 강의 조회 Pagination 추가, 페이지 검증 어노테이션 추가, HTTP Method "POST" 방식으로 변경
  src/main/java/com/example/satto/domain/currentLecture/controller/CurrentLectureController.java
  src/main/java/com/example/satto/domain/currentLecture/converter/CurrentLectureConverter.java
  src/main/java/com/example/satto/domain/currentLecture/dto/CurrentLectureListResponseDTO.java
  src/main/java/com/example/satto/domain/currentLecture/repository/CurrentLectureRepositoryCustom.java
  src/main/java/com/example/satto/domain/currentLecture/repository/impl/CurrentLectureRepositoryImpl.java
  src/main/java/com/example/satto/domain/currentLecture/service/CurrentLectureService.java
  src/main/java/com/example/satto/global/annotation/CheckPage.java
  src/main/java/com/example/satto/global/annotation/validator/CheckPageValidator.java
Labels: :sparkles: Feature

#142 refactor: UsersController 리팩토링
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
Labels: :recycle: Refactor

#143 :sparkles: [FEATURE] 강의명 검색 방식 수정, 싸강 여부 검색 옵션 추가
  src/main/java/com/example/satto/domain/currentLecture/repository/impl/CurrentLectureRepositoryImpl.java
Labels: :sparkles: Feature

#145 refactor : 대표시간표 설정 로직 수정
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :recycle: Refactor

#147 feature : 필수로 수강할 강의 예외 처리
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :sparkles: Feature

#150 feature : TimeTable 강의 수정 기능 추가
  src/main/java/com/example/satto/domain/timeTable/controller/TimeTableController.java
  src/main/java/com/example/satto/domain/timeTable/dto/UpdateTimeTableLectRequestDTO.java
  src/main/java/com/example/satto/domain/timeTable/dto/UpdateTimeTableRequestDTO.java
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
  src/main/java/com/example/satto/domain/timeTableLecture/repository/TimeTableLectureRepository.java
  src/main/java/com/example/satto/domain/timeTableLecture/service/TimeTableLectureService.java
Labels: :sparkles: Feature

#151 feature : 타 사용자 시간표 조회 기능 추가
  src/main/java/com/example/satto/domain/timeTable/controller/TimeTableController.java
  src/main/java/com/example/satto/domain/timeTable/repository/TimeTableRepository.java
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :sparkles: Feature

#152 refactor : 코드 수정
  src/main/java/com/example/satto/domain/timeTable/controller/TimeTableController.java
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :recycle: Refactor

#154 feature : TimeTable 자동 생성 필터링 제외 버전 추가
  src/main/java/com/example/satto/domain/timeTable/controller/TimeTableController.java
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :sparkles: Feature

#155 refactor : 코드 수정
  src/main/java/com/example/satto/domain/timeTable/controller/TimeTableController.java
Labels: :recycle: Refactor

#158 refactor: Follow 로직 리팩토링
  src/main/java/com/example/satto/domain/follow/service/Impl/FollowServiceImpl.java
Labels: :recycle: Refactor

#160 refactor : 타인 시간표 조회 로직 수정
  src/main/java/com/example/satto/domain/timeTable/repository/TimeTableRepository.java
  src/main/java/com/example/satto/domain/timeTable/service/TimeTableService.java
Labels: :recycle: Refactor

#162 ✨ [FEATURE] 유저 검색 기능
  src/main/java/com/example/satto/domain/users/controller/UsersController.java
  src/main/java/com/example/satto/domain/users/converter/UsersConverter.java
  src/main/java/com/example/satto/domain/users/repository/UsersRepository.java
  src/main/java/com/example/satto/domain/users/repository/querydsl/Impl/UsersRepositoryCustomImpl.java
  src/main/java/com/example/satto/domain/users/repository/querydsl/UsersRepositoryCustom.java
  src/main/java/com/example/satto/domain/users/service/Impl/UsersServiceImpl.java
  src/main/java/com/example/satto/domain/users/service/UsersService.java
Labels: :sparkles: Feature

#164 [FEATURE][CHORE] 공개 프로필 팔로우, 팔로워 기능
  src/main/java/com/example/satto/domain/follow/controller/FollowController.java
  src/main/java/com/example/satto/domain/follow/service/Impl/FollowServiceImpl.java
Labels: :sparkles: Feature, 🧹Chore

#166 :sparkles: feat: 사진 업로드 관련 S3 환경 및 설정 수정, 이벤트 도메인 API 오류 수정
  src/main/java/com/example/satto/S3/FileFolder.java
  src/main/java/com/example/satto/S3/service/FileUploadService.java
  src/main/java/com/example/satto/config/OpenApiConfig.java
  src/main/java/com/example/satto/config/S3Component.java
  src/main/java/com/example/satto/config/S3Config.java
  src/main/java/com/example/satto/domain/event/controller/PhotoContestController.java
  src/main/java/com/example/satto/domain/event/controller/TimetableContestController.java
  src/main/java/com/example/satto/domain/event/dto/PhotoContestResponseDto.java
  src/main/java/com/example/satto/domain/event/dto/TimetableContestResponseDto.java
  src/main/java/com/example/satto/domain/event/repository/EventRepository.java
  src/main/java/com/example/satto/domain/event/repository/impl/EventRepositoryCustomImpl.java
  src/main/java/com/example/satto/domain/event/service/EventService.java
  src/main/java/com/example/satto/domain/event/service/impl/EventServiceImpl.java
  src/main/java/com/example/satto/global/common/code/status/ErrorStatus.java
  src/main/java/com/example/satto/s3/S3Manager.java
  src/main/java/com/example/satto/s3/uuid/Uuid.java
  src/main/java/com/example/satto/s3/uuid/UuidRepository.java
  src/main/java/com/example/satto/s31/FileDownloadFailedException.java
  src/main/java/com/example/satto/s31/FileFolder.java
  src/main/java/com/example/satto/s31/FileService.java
  src/main/java/com/example/satto/s31/S3Component.java
  src/main/java/com/example/satto/s31/S3Service.java
Labels: :sparkles: Feature
